#!/bin/sh

# Copyright (c) 01/03/2017 The Bitland SW. All rights reserved.
# choose one RMA to modify
# cd /mnt/factory/dev_image/factory/py/test/test_lists/  [unfinished]
# choose "U" to umount /mnt/factory/   [unfinished] 


echo
cat << EOF
*****pelase enter your choise:(1-3)*****
echo
1.Mount US_RMA.bin
2.Mount WW_RMA.bin
3.Exit
EOF
echo
read -p "Now select the top option to: " Input
case $Input in
  1) 		
		echo "Running Command :./mount_partition.sh ../../US_RMA.bin 1 /mnt/factory/"
		~/Desktop/N23_RMA/ChromeOS-factory-R52-8182.47.0-hana/factory_setup/mount_partition.sh ~/Desktop/N23_RMA/US_RMA.bin 1 /mnt/factory/
		echo "Mount US=======US========US==================================="
	;;
  2)
		echo "Running Command :./mount_partition.sh ../../WW_RMA.bin 1 /mnt/factory/"
		~/Desktop/N23_RMA/ChromeOS-factory-R52-8182.47.0-hana/factory_setup/mount_partition.sh ~/Desktop/N23_RMA/WW_RMA_force.bin 1 /mnt/factory/
		echo "Mount WW=======WW========WW==================================="
	;;
esac






